#!/usr/bin/env node

import { CONTENT_PR_PREFIX, PERFORMANCE_PR_PREFIX, REPO_ROOT, appendStepSummary } from './common.mjs';

function getGitHubContext() {
  const repository = process.env.GITHUB_REPOSITORY?.trim();
  const token = process.env.GITHUB_TOKEN?.trim();

  if (!repository || !token) {
    throw new Error('GITHUB_REPOSITORY and GITHUB_TOKEN are required for PR automation.');
  }

  const [owner, repo] = repository.split('/');
  if (!owner || !repo) {
    throw new Error(`Invalid GITHUB_REPOSITORY value: ${repository}`);
  }

  return { owner, repo, token };
}

async function githubRequest(pathname, options = {}) {
  const { owner, repo, token } = getGitHubContext();
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}${pathname}`, {
    method: options.method ?? 'GET',
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      'User-Agent': 'ai-security-brief-automation',
    },
    body: options.body ? JSON.stringify(options.body) : undefined,
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`GitHub API request failed with ${response.status}: ${body}`);
  }

  if (response.status === 204) {
    return null;
  }

  return response.json();
}

export function buildPullRequestBody({
  kind,
  weekKey,
  effectiveDate,
  branchName,
  model,
  outputs,
  notes = [],
}) {
  const heading = kind === 'performance' ? PERFORMANCE_PR_PREFIX : CONTENT_PR_PREFIX;
  const lines = [
    `## ${heading}${weekKey}`,
    '',
    `- Branch: \`${branchName}\``,
    `- Effective date: \`${effectiveDate}\``,
    ...(model ? [`- Model: \`${model}\``] : []),
    '',
    '### Outputs',
    ...outputs.map((output) => `- ${output}`),
    '',
    '### Review',
    '- Human review is required before merge.',
    '- Generated by GitHub Actions and API-backed automation.',
  ];

  if (notes.length > 0) {
    lines.push('', '### Notes', ...notes.map((note) => `- ${note}`));
  }

  return `${lines.join('\n')}\n`;
}

export async function ensureDraftPullRequest({
  branchName,
  title,
  body,
}) {
  const { owner } = getGitHubContext();
  const existing = await githubRequest(`/pulls?state=open&head=${encodeURIComponent(`${owner}:${branchName}`)}&base=main`);

  if (Array.isArray(existing) && existing.length > 0) {
    const current = existing[0];
    await githubRequest(`/pulls/${current.number}`, {
      method: 'PATCH',
      body: {
        title,
        body,
      },
    });
    return {
      number: current.number,
      htmlUrl: current.html_url,
      created: false,
    };
  }

  const created = await githubRequest('/pulls', {
    method: 'POST',
    body: {
      title,
      head: branchName,
      base: 'main',
      body,
      draft: true,
    },
  });

  return {
    number: created.number,
    htmlUrl: created.html_url,
    created: true,
  };
}

export async function summarisePullRequest(result, branchName) {
  const lines = [
    '### Draft PR',
    result
      ? `- ${result.created ? 'Created' : 'Updated'} draft PR [#${result.number}](${result.htmlUrl}) from \`${branchName}\``
      : `- Dry run only. No PR created for \`${branchName}\``,
  ];

  await appendStepSummary(lines);
}
